### ISSUE TITLE
Dynamic Wait Time

### ISSUE THREAD

**Issue by marckaraujo** [horike37/serverless-step-functions#114]
# This is a Feature Proposal

## Description

For feature proposals:
Is possible to have dynamic wait time to execute a step function?

Ex.
1. Step function will be trigged by the API with a json.
2. This json will have the wait time to execute the next step function.
3. The next step function executes after the waiting time.

**Comment by horike37** [comment]
Hi @marckaraujo 
I'm not sure how to resolve the problem but we can wait to collect opinions or feedback from someone else.

**Comment by theburningmonk** [comment]
@marckaraujo can you not do this with a `Wait` state already by specifying `SecondsPath` or `TimestampPath`?

**Comment by theburningmonk** [comment]
closing since it's idle for a while
