### ISSUE TITLE
Populate variables before parsing serverless.yml

### ISSUE THREAD

**Issue by lucas-rudd** [horike37/serverless-step-functions#117]
# This is a Feature Proposal

## Description

* What is the use case that should be solved.
Currently this plugin is setting the step function, state machine, and activity keys before the serverless.yml file has populated the variables.

This allows you to organize serverless.yml like such:

```
stepFunctions:
  stateMachines:
    ${file(config/env/${opt:stage}.yml):stateMachines}
```
but not like this

```
stepFunctions:
  ${file(config/env/${opt:stage}.yml):stepFunctions}
```

I've got a PR out to fix this already #116 

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.24.1
* ***The Plugin Version you're using***: 1.4.0

**Comment by horike37** [comment]
just released this fix with v1.4.1.
Thank @lucas-rudd :smile:
