### ISSUE TITLE
Support Tasks Deployment

### ISSUE THREAD

**Issue by paulopontesm** [horike37/serverless-step-functions#12]
It would be cool to be able to create new tasks and reference them from the workflow
Maybe something like this:
```
tasks
  MyTask:
    name: my_task_custom_name_${self:provider.stage}
```

**Comment by horike37** [comment]
Greate idea @paulopontesm !
just set the next milestone.

**Comment by horike37** [comment]
I just is out v0.4.0. It is supported Tasks now.
Please show the README. thx!
