### ISSUE TITLE
Shared API Gateway support for HTTP Endpoints

### ISSUE THREAD

**Issue by vlewin** [horike37/serverless-step-functions#130]
# This is a Feature Proposal

Please add support for [Shared API Gateway](https://serverless.com/framework/docs/providers/aws/events/apigateway/#share-api-gateway-and-api-resources)

## Description

* Add shared api gateway support
* No config required

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.28.0
* ***The Plugin Version you're using***: latest
* ***Operating System***: Mac OS X

**Comment by vlewin** [comment]
Working but not fully tested adaptations: https://github.com/horike37/serverless-step-functions/compare/master...vlewin:master

Tested with my demo project. API endpoint was properly attached to restApiId/restApiRootResourceId

**Comment by horike37** [comment]
Hi @vlewin 
Thank you for the proposal! That's a great idea!
Could you send a PR with current working status so that we can test and review?
