### ISSUE TITLE
Is there any way to set up deadletter queues with this plugin?

### ISSUE THREAD

**Issue by vayias** [horike37/serverless-step-functions#132]
First of all @horike37, great plugin and great work!! 

I was wondering if there is currently a way to set up deadletter sqs queues through 
`serverless-step-functions`. 

I tried to achieve that using the [serverless-plugin-lambda-dead-letter](https://github.com/gmetzker/serverless-plugin-lambda-dead-letter) but I was unsuccessful, so I was wondering if `serverless-step-functions` and `serverless-plugin-lambda-dead-letter` don't work well together.

I also created an issue [here](https://github.com/gmetzker/serverless-plugin-lambda-dead-letter/issues/36)

**Comment by theburningmonk** [comment]
Lambda's dead letter queue support only applies to async event sources - SNS, CloudWatch Event, etc. not synchronous invocations from Step Functions. See the [official doc](https://docs.aws.amazon.com/lambda/latest/dg/dlq.html).
