### ISSUE TITLE
that.sdk[service] is not a constructor

### ISSUE THREAD

**Issue by lielran** [horike37/serverless-step-functions#14]
using version 0.2.0

```
 sls deploy stepf  --state <stepfunctionname>
```
Serverless: Start to deploy registerFlow step function...

  Type Error ---------------------------------------------

     that.sdk[service] is not a constructor

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.2.1
     Serverless Version: 1.3.0

**Comment by horike37** [comment]
@lielran 
Thank you for using and reporting!
Sorry the plugin can't work with Serverless v1.3 or lower. Please update Serverless latest version 1.5, then try again.

**Comment by lielran** [comment]
Got it. Thanks!

**Comment by lielran** [comment]
fixed the issue.
