### ISSUE TITLE
Support tagging

### ISSUE THREAD

**Issue by noahw3** [horike37/serverless-step-functions#166]
# This is a Feature Proposal

## Description

* AWS recently added support for tagging for step functions. It'd be wonderful if this plugin could support tags. I'd imagine it'd be a field alongside role, definition, etc.
* Unfortunately there's no support on the [CreateStepFunction API](https://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateStateMachine.html) right now, meaning that it's not in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html) either. It's in separate [TagResource](https://docs.aws.amazon.com/step-functions/latest/apireference/API_TagResource.html) and [UntagResource](https://docs.aws.amazon.com/step-functions/latest/apireference/API_UntagResource.html) calls ([ListTagsByResource](https://docs.aws.amazon.com/step-functions/latest/apireference/API_ListTagsForResource.html) also exists).

**Comment by theburningmonk** [comment]
looks like tags are supported now! yay! 

![image](https://user-images.githubusercontent.com/546969/54378638-b2455a00-46c2-11e9-875f-e48338147107.png)

**Comment by theburningmonk** [comment]
released as part of v1.15.0
