### ISSUE TITLE
Type Error: this.provider.getApiGatewayPredefinedResources is not a function

### ISSUE THREAD

**Issue by yashwant** [horike37/serverless-step-functions#173]
# This is a (Bug Report / Feature Proposal)
I am getting error when I try to deploy ServerLess function. Error log is as follows:

state machine [myStateMachine] : alarms config is malformed. Please see https://github.com/horike37/serverless-step-functions for examples
 
  Type Error ---------------------------------------------
 
     this.provider.getApiGatewayPredefinedResources is not
     a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: this.provider.getApiGatewayPredefinedResources is not a function
    at ServerlessStepFunctions.getResourcePaths (node_modules/serverless-step-functions/lib/deploy/events/apiGateway/resources.js:61:47)
    at ServerlessStepFunctions.compileResources (node_modules/serverless-step-functions/lib/deploy/events/apiGateway/resources.js:9:37)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:246:17)
    at Deploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:79:48)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:77:8)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:55)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:96:33)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:87:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       8.15.0
     Serverless Version: 1.13.2
 

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

My serverless.yml file is as follows:

service: serverlessStepFunctions

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(./aws_params.yml):profile}
  stage: ${file(./aws_params.yml):stage}
  region: ${file(./aws_params.yml):region}
  deploymentBucket: ${file(./aws_params.yml):DEPLOYMENT_S3_BUCKET}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action: "*:*"
        # - "states:StartExecution"
      Resource:
        - "*"

  stackPolicy: 
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
    - Effect: Deny
      Principal: "*"
      Action:
        - Update:Replace
        - Update:Delete
      Condition:
        StringEquals:
          ResourceType:
            - AWS::EC2::Instance

  environment:
    AccountId: ${file(./aws_params.yml):AccountId}

functions:
  function1:
    handler: handler.hello1
  function2:
    handler: handler.hello2
  function3:
    handler: handler.hello3
  function4:
    handler: handler.hello4
  function5:
    handler: handler.hello5

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: myStateMachine
      events:
        - http:
            path: function1
            method: get
      definition:
        Comment: "An example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource: "<function ARN of function1 >"
            End: true

My aws_params.yml config file is as follows:
region: <region>
stage: <stage name>
profile: <aws profile>
DEPLOYMENT_S3_BUCKET: <deployment bucket name>
AccountId: <AWS account id>

## Additional Data
* ***Serverless Framework Core Version you're using***:
* ***The Plugin Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by theburningmonk** [comment]
Could you put the serverless.yml in a code block so the formatting is preserved? Makes it easier for me to put it into a project and try it out myself

**Comment by yashwant** [comment]
Serverless.yml

`
service: serverlessStepFunctions

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(./aws_params.yml):profile}
  stage: ${file(./aws_params.yml):stage}
  region: ${file(./aws_params.yml):region}
  deploymentBucket: ${file(./aws_params.yml):DEPLOYMENT_S3_BUCKET}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action: "*:*"
        # - "states:StartExecution"
      Resource:
        - "*"

  stackPolicy: 
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
    - Effect: Deny
      Principal: "*"
      Action:
        - Update:Replace
        - Update:Delete
      Condition:
        StringEquals:
          ResourceType:
            - AWS::EC2::Instance

  environment:
    AccountId: ${file(./aws_params.yml):AccountId}

functions:
  function1:
    handler: handler.hello1
  function2:
    handler: handler.hello2
  function3:
    handler: handler.hello3
  function4:
    handler: handler.hello4
  function5:
    handler: handler.hello5

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: myStateMachine
      events:
        - http:
            path: function1
            method: get
      definition:
        Comment: "An example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource: "<function ARN of function1 >"
            End: true
`

aws_params.yml

`
region: <>
stage: <>
profile: <>
DEPLOYMENT_S3_BUCKET: <>
AccountId: <>
`

**Comment by theburningmonk** [comment]
what version of the Serverless framework are you using?

**Comment by yashwant** [comment]
Serverless Version: 1.13.2

**Comment by theburningmonk** [comment]
Try updating the serverless framework to latest, the error `this.provider.getApiGatewayPredefinedResources is not a function` suggest the plugin is depending on something that got added to the serverless framework after `1.13.2`. I just tried your serverless.yml with the latest version of serverless framework and it went through fine.

**Comment by theburningmonk** [comment]
If you update the plugin to `1.12.1` you won't see the the `state machine [myStateMachine] : alarms config is malformed. Please see https://github.com/horike37/serverless-step-functions for examples` message either. It was fixed by #171

**Comment by yashwant** [comment]
Thanks @theburningmonk. Changing ServerLess version works. I am closing the issue.

**Comment by theburningmonk** [comment]
👍 no probs, glad I could help!
