### ISSUE TITLE
Feature Proposal: Possible to create a step function without creating a new lambda?

### ISSUE THREAD

**Issue by AnthonyWC** [horike37/serverless-step-functions#175]
# Feature Proposal

Is it possible to create a step function without creating a new lambda?  The step function would reference other existing lambdas. Currently I just create a mock lambda in order to satisfy that requirement.  Perhaps this is a limitation of serverless framework itself (and not something that can be handled by the plugin)?

**Comment by theburningmonk** [comment]
@AnthonyWC this is already possible with the serverless framework and this plugin. For example, see [this](https://github.com/theburningmonk/complete-guide-to-step-functions-examples/blob/master/Other%20services/SNS/serverless.yml).

**Comment by AnthonyWC** [comment]
Oh nice. :)
