### ISSUE TITLE
How to pass parameters to a task state for the new supported service API?

### ISSUE THREAD

**Issue by ahmedezzeldin93** [horike37/serverless-step-functions#185]
This is a question/ feature proposal if not there already

How to pass parameters to a task state for the new supported service API (Glue/Batch/Sagemaker)?

I would like to add those parameters as described in https://docs.aws.amazon.com/step-functions/latest/dg/connectors-parameters.html

You already have support as fixed in #179

**Comment by theburningmonk** [comment]
It should be supported already, although I don't know what the specific parameters are. Here's an example of how to pass parameters to SNS: https://github.com/theburningmonk/complete-guide-to-step-functions-examples/blob/master/Other%20services/SNS/serverless.yml#L23-L29

**Comment by theburningmonk** [comment]
Closing since it's been idle for a while.
