### ISSUE TITLE
Activities?

### ISSUE THREAD

**Issue by justinmchase** [horike37/serverless-step-functions#19]
Can you declare activities?

I realize the implementation of the activity would not be serverless, and therefore out of the scope of this, but how would you declare an activity task in the step-function with this plugin?

**Comment by horike37** [comment]
Thank you for opening @justinmchase !
It is not supported activities now. But it will be supported for next version.
Please wait a little longer.

**Comment by horike37** [comment]
@justinmchase 
It is out v0.4.0 today. It is supported activities now!
Please see the README for detail.

**Comment by justinmchase** [comment]
Excellent, thanks! Trying it out now.

**Comment by apedzko** [comment]
@justinmchase  Is there any chance that you could provide an example of a step function with an activity as one of its tasks?

**Comment by justinmchase** [comment]
Sorry, I don't even work on this codebase anymore, I think the docs covered it though.
