### ISSUE TITLE
Feature: support Status Change notification

### ISSUE THREAD

**Issue by theburningmonk** [horike37/serverless-step-functions#197]
# This is a Feature Proposal

## Description

You can monitor the execution of your state machines [via CloudWatch Events](https://aws.amazon.com/about-aws/whats-new/2019/05/aws-step-functions-adds-support-for-workflow-execution-events/) now.

It will be great to add support for it in the plugin so you can configure them alongside your state machine definition, e.g.

```
stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: test
      definition:
        ...
      notifications:
        ABORTED:
          - sns: SNS_TOPIC_ARN
          - sqs: SQS_TOPIC_ARN
          - sqs: # more config options
              arn: SQS_TOPIC_ARN
              messageGroupId: 12345
          - lambda: LAMBDA_FUNCTION_ARN
          - kinesis: KINESIS_STREAM_ARN
          - kinesis:  # more config options
               arn: KINESIS_STREAM_ARN
               partitionKeyPath: $.user_id
          - firehose: FIREHOSE_STREAM_ARN
          - stepFunctions: STATE_MACHINE_ARN
        FAILED:
          ... # same as above
        RUNNING:
          ... # same as above
        SUCCEEDED:
          ... # same as above
        TIMED_OUT:
          ... # same as above
```

**Comment by horike37** [comment]
@theburningmonk 
Thank you for the proposal 👍 
Sure, let's support for it.

**Comment by horike37** [comment]
Have this already support for CloudFormation? Since the all deployment is running via it for consistency.

**Comment by theburningmonk** [comment]
I assume so. There's no change to the cloud formation structure, just pass in a different value for event-detail.

**Comment by horike37** [comment]
OK. No problem 👍
