### ISSUE TITLE
Declaring step functions with activities

### ISSUE THREAD

**Issue by apedzko** [horike37/serverless-step-functions#199]
Hi All! Could anyone point me to an example of declaring a step function where one of the states in the state machine is an activity that is processed by an external activity worker?
Will appreciate a prompt response.

**Comment by theburningmonk** [comment]
@apedzko you can find an example of a state machine with activity [here](https://github.com/theburningmonk/complete-guide-to-step-functions-examples/tree/master/Activities). I covered activities in my [video course](https://theburningmonk.thinkific.com/courses/complete-guide-to-aws-step-functions) on step functions, but I didn't show how you'd use a Lambda to complete the activity but did it through the AWS CLI instead. Ultimately it's the same API calls you'll have to make through Lambda - to poll activity tasks, do them, and then completing the task.

**Comment by apedzko** [comment]
@theburningmonk, many thanks - this is exactly what i was looking for.

**Comment by apedzko** [comment]
The example has been provided by @theburningmonk

**Comment by apedzko** [comment]
@theburningmonk Yan, please excuse me for asking that many questions, however is there any example of passing a payload parameter to an activity to be consumed by the activity worker?

**Comment by theburningmonk** [comment]
@apedzko there's no need for passing data to the activity explicitly, the current value of `$` is passed to the activity in the `input` attribute.

Like this:

![image](https://user-images.githubusercontent.com/546969/57714571-b7943600-766c-11e9-88ca-5453f500116c.png)

**Comment by apedzko** [comment]
Thanks!

вт, 14 мая 2019 г., 19:21 Yan Cui <notifications@github.com>:
