### ISSUE TITLE
Issue running the following with our build

### ISSUE THREAD

**Issue by jaronimo99** [horike37/serverless-step-functions#20]
Not sure why the state is required. The docs specify that it shouldn't be required. When we specify a state, it doesn't work either.
![2239990e-ed3b-11e6-88f4-afc1d4946ba7](https://cloud.githubusercontent.com/assets/5075984/23090035/4bf59e5a-f551-11e6-8454-7006617922d6.png)

**Comment by horike37** [comment]
Thank you for opening @jaronimo99 !
What version are you using? 
Since v0.3.0, the state is no longer required. 
If it is a lower version, that error will occur when state is omitted.
