### ISSUE TITLE
Implementing Fanout Pattern: Help Wanted

### ISSUE THREAD

**Issue by sreimer15** [horike37/serverless-step-functions#206]
## Description

Hi, 

I'm wondering if there is a way to implement a fanout pattern with step functions to correlate otherwise unrelated lambda executions. As an example:
Step 1: 
Take a payload of say 10 ids and do some processing

Step 2: 

Each id gets assigned into its own lambda execution (assuming these are relatively long running) and if one of the lambda executions terminally fails (with a set number of retries) fail the whole step (all 10 executions) and go back to step 1. 

and if all of those lambdas pass then go onto step 2 knowing all of those tasks succeeded.

Is that something that makes sense to model in step functions? 

Thank you for any help anyone could be, I appreciate it!

**Comment by wanghq** [comment]
This is fundamentally [not supported by Step Functions](https://forums.aws.amazon.com/thread.jspa?threadID=244196&tstart=0) so I don't think it's doable with the plugin. 

What you asked is like a foreach where all its iterations run in parallel. I have a poll asking for opinions about how to name this "control". Would you mind making a vote? Thanks!

https://twitter.com/wanghq/status/1159625221529194496

Disclosure: I work for Alibaba Cloud and we beta released a similar service called Function Flow. [This sample project](https://github.com/awesome-fnf/oss-batch-process/blob/master/flows/oss-flow.yaml#L39) shows how we solve the problem.

**Comment by slootjes** [comment]
This is now possible using Dynamic Parallelism/Map Type : https://aws.amazon.com/blogs/aws/new-step-functions-support-for-dynamic-parallelism/

**Comment by theburningmonk** [comment]
Closing as this has been answered. Also, if anyone's interested I cover the Map state in my [Step Functions](https://theburningmonk.thinkific.com/courses/complete-guide-to-aws-step-functions) course as well.
