### ISSUE TITLE
IamRoleStateMachineExecution - Forces a CreateRole, can this be assumed from provider or set

### ISSUE THREAD

**Issue by ksteigerwald** [horike37/serverless-step-functions#210]
# Feature Proposal
When the provider role is set, use the provider as the primary role to create state machines and step functions. Currently, it will execute:
CloudFormation - CREATE_FAILED - AWS::IAM::Role - IamRoleStateMachineExecution

An error occurred: IamRoleStateMachineExecution - API: iam:CreateRole User: arn:aws:sts::myacct:assumed-role/MYASSUMEDROLE/MYCOMPANYHANDLE is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::MYACCT:role/MYHANDLER-IamRoleStateMachineExecution-OF9ZZQG4GM65.

## Description

For feature proposals:

- Allow provider role to be assumed for all creation steps
- Allow role to specified for IamRoleStateMachineExecution

Similar or dependent issues:
* #12345

## Additional Data
* ***Serverless Framework Core Version you're using***:
* ***The Plugin Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by theburningmonk** [comment]
@ksteigerwald this looks like whatever role you're using to deploy the serverless project doesn't have the necessary permission to create IAM roles (which this plugin does). Have a look at the IAM policy for the `arn:aws:sts::myacct:assumed-role/MYASSUMEDROLE/MYCOMPANYHANDLE` role you're using to run `sls deploy`.

**Comment by ksteigerwald** [comment]
@theburningmonk Yes, at our company we are not allowed to create IAM roles, hence the reason for the request. Why must a role be created versus utilized? The role that I deploy under has the needed permissions.

**Comment by ciraki** [comment]
This is an issue for me also. We make use of permission boundaries in AWS to manage and avoid privilege escalation. A role can be created via serverless framework (as a resource) so long as it has the permission boundary attached. If this resource could be provided optionally for a variety of things such as the state machine and the apigateway event, that would be most helpful.

**Comment by theburningmonk** [comment]
You can already override the state machine execution role (see below), and we just added support (via #208) for using a custom role for API Gateway as well.

```yml
stepFunctions:
  stateMachines:
    myStateMachine:
      role: <ARN to custom IAM role>
      definition:
        ...
```

**Comment by ksteigerwald** [comment]
Awesome, that works! Big thanks @theburningmonk

**Comment by santhosh-vikraman** [comment]
I am getting this issue. Even if a role is specified, I am getting error. 
```
Encountered a permissions error applying tags, please add required tag permissions. 
Retrying request without including tags.
Details: "User: arn:aws:sts::ID:assumed-role/cloudformation-execution-role/AWSCloudFormation 
is not authorized to perform: iam:CreateRole on resource: arn:aws:iam:::role/-d-<statemachinename>-1SR9DY6N0YRUP
 with an explicit deny in a permissions boundary
```
