### ISSUE TITLE
Serverless failing to find States key word while deploying stepfunctions

### ISSUE THREAD

**Issue by sptasxm** [horike37/serverless-step-functions#213]
# This is a (Bug Report / Feature Proposal)

## Description

Getting below exception while deploying a step function using serverless.

TypeError: Cannot read property 'States' of undefined
    at getAllStateMachines.forEach (/Users/spitta/cps-retry-backoff-function/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:289:67)
    at Array.forEach (<anonymous>)
    at ServerlessStepFunctions.compileIamRole (/Users/spitta/cps-retry-backoff-function/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:285:32)

## Additional Data
* ***Serverless Framework Core Version you're using***:
     OS:                     darwin
     Node Version:           10.14.2
     Serverless Version:     1.44.1
servser
* ***The Plugin Version you're using***:
* ***Operating System***:
macos
* ***Stack Trace***:
1.23.0
* ***Provider Error messages***:
TypeError: Cannot read property 'States' of undefined
    at getAllStateMachines.forEach (/Users/spitta/cps-retry-backoff-function/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:289:67)
    at Array.forEach (<anonymous>)
    at ServerlessStepFunctions.compileIamRole (/Users/spitta/cps-retry-backoff-function/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:285:32)
[serverless.txt](https://github.com/horike37/serverless-step-functions/files/3267096/serverless.txt)

**Comment by theburningmonk** [comment]
@sptasxm can you paste your state machine definition here?

**Comment by sptasxm** [comment]
I have attached the server less script to the issue. Do you want me to post the json?

**Comment by theburningmonk** [comment]
Yes. Everything under `stepFunctions`, so I can try to replicate the issue.

e.g.

```yml
stepFunctions:
  stateMachines:
    ...
```

**Comment by sptasxm** [comment]
Here it is:

stepFunctions:
    stateMachines:
       retry-backoff-state-machine:
           name: retry-backoff-state-machine-${self:provider.stage}
           definintion:
               Comment: State machine for retrying lambda failures
               StartAt: ComputeBackoff
               States:
                   ComputeBackoff:
                       Type: Task
                       Resource:
                            Fn::GetAtt: [retry-backoff-lambda, Arn]
                       Catch:
                            ErrorEquals: States.ALL
                            Next: PublishtoDLQ
                            ResultPath: "$.error"
                       Next: Wait
                   Wait:
                       Type: Wait
                       SecondsPath: "$.expiryseconds"
                       Next: Publishtotopic
                   Publishtotopic:
                       Type: Task
                       Resource: arn:aws:states:::sns:publish
                       Parameters:
                           Message.$: "$"
                           TopicArn.$: "$.topic_arn"
                       Catch:
                             ErrorEquals: States.ALL
                             Next: PublishtoDLQ
                             ResultPath: "$.error"
                       End: true
                   PublishtoDLQ:
                       Type: Task
                       Resource: arn:aws:states:::sqs:sendMessage
                       Parameters:
                           MessageBody.$: "$.*"
                           QueueUrl: ${ssm:/lambda/event-aggregator/${self:provider.stage}/dlq-endpoint}
                       End: true

**Comment by sptasxm** [comment]
stepFunctions:
    stateMachines:
       retry-backoff-state-machine:
           name: retry-backoff-state-machine-${self:provider.stage}
           definintion:
               Comment: State machine for retrying lambda failures
               StartAt: ComputeBackoff
               States:
                   ComputeBackoff:
                       Type: Task
                       Resource:
                            Fn::GetAtt: [retry-backoff-lambda, Arn]
                       Catch:
                            ErrorEquals: States.ALL
                            Next: PublishtoDLQ
                            ResultPath: "$.error"
                       Next: Wait
                   Wait:
                       Type: Wait
                       SecondsPath: "$.expiryseconds"
                       Next: Publishtotopic
                   Publishtotopic:
                       Type: Task
                       Resource: arn:aws:states:::sns:publish
                       Parameters:
                           Message.$: "$"
                           TopicArn.$: "$.topic_arn"
                       Catch:
                             ErrorEquals: States.ALL
                             Next: PublishtoDLQ
                             ResultPath: "$.error"
                       End: true
                   PublishtoDLQ:
                       Type: Task
                       Resource: arn:aws:states:::sqs:sendMessage
                       Parameters:
                           MessageBody.$: "$.*"
                           QueueUrl: ${ssm:/lambda/event-aggregator/${self:provider.stage}/dlq-endpoint}
                       End: true

**Comment by theburningmonk** [comment]
I see what the problem is. You have a typo at 'defintion'. The error message can be clearer.

**Comment by sptasxm** [comment]
:( didn't realise that. Thank you for finding it. will close this issue.
