### ISSUE TITLE
Serverless deploy: Unexpected token

### ISSUE THREAD

**Issue by f766** [horike37/serverless-step-functions#218]
Using serverless-step-functions for the first time, have previously deployed code using Serverless framework.

Stack Trace:
```
15:13:20 $ serverless deploy -s dev -r us-east-2
15:13:20 Serverless: Load command config
15:13:20 Serverless: Load command config:credentials
15:13:21 Serverless: Load command create
15:13:21 Serverless: Load command install
15:13:21 Serverless: Load command package
15:13:21 Serverless: Load command deploy
15:13:21 Serverless: Load command deploy:function
15:13:21 Serverless: Load command deploy:list
15:13:21 Serverless: Load command deploy:list:functions
15:13:21 Serverless: Load command invoke
15:13:21 Serverless: Load command invoke:local
15:13:21 Serverless: Load command info
15:13:21 Serverless: Load command logs
15:13:21 Serverless: Load command metrics
15:13:21 Serverless: Load command print
15:13:21 Serverless: Load command remove
15:13:21 Serverless: Load command rollback
15:13:21 Serverless: Load command rollback:function
15:13:21 Serverless: Load command slstats
15:13:21 Serverless: Load command plugin
15:13:21 Serverless: Load command plugin
15:13:21 Serverless: Load command plugin:install
15:13:21 Serverless: Load command plugin
15:13:21 Serverless: Load command plugin:uninstall
15:13:21 Serverless: Load command plugin
15:13:21 Serverless: Load command plugin:list
15:13:21 Serverless: Load command plugin
15:13:21 Serverless: Load command plugin:search
15:13:21 Serverless: Load command config
15:13:21 Serverless: Load command config:credentials
15:13:21 Serverless: Load command rollback
15:13:21 Serverless: Load command rollback:function
15:13:22  
15:13:22   Syntax Error -------------------------------------------
15:13:22  
15:13:22   Unexpected token ...
15:13:22  
15:13:22      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
15:13:22  
15:13:22   Stack Trace --------------------------------------------
15:13:22  
15:13:22 SyntaxError: Unexpected token ...
15:13:22 /srv/jenkins/workspace/***/node_modules/@hapi/hoek/lib/deep-equal.js:17
15:13:22     options = { prototype: true, ...options };
15:13:22                                  ^^^
```

Deploy setup commands:
```
        - "npm init -f"
        - "npm install serverless-aws-documentation"
        - "npm install serverless-reqvalidator-plugin"
        - "npm install -g serverless"
        - "npm install serverless-step-functions"
```

Runs inside docker image: sea/centos7-agent-complete:0.3.6

serverless-aws-documentation@1.1.0 
serverless-reqvalidator-plugin@1.0.3 
/srv/jenkins/.nvm/versions/node/v6.10.3/lib
serverless@1.45.1 
serverless-step-functions@1.24.1

Please let me know if my setup was incorrect or if there is a versioning issue, or something else.

**Comment by f766** [comment]
I appear to be able to get past this bug locally: 
MacOS 10.14.5
npm --version: 6.1.0

**Comment by kzhou57** [comment]
It seems an issue introduced recently. And i have reverted to back version 1.19.2 and this issue is gone. 

So the workaround is to lock to older version 1.19.2 . 

In other thread, it sounds like upgrade your node version to 10, also fix the problem. However I didn't try it myself, and it's bigger problem for me to upgrade node version 

npm --version
6.9.0

**Comment by theburningmonk** [comment]
@f766 it looks like an issue with the version of node you're running. You need to node8 or above, we stopped support for node4 and 6 since they have been deprecated by Lambda.

**Comment by f766** [comment]
@theburningmonk Thank you! I don't have much node experience and didn't realize npm is just the package manager, not node itself. My node version in the image was 6.x.
I was able in my deploy script to call "nvm use 8" and I got past this issue.

Thanks!
And thanks for creating this plugin!
