### ISSUE TITLE
Deploy through cloudformation

### ISSUE THREAD

**Issue by paulopontesm** [horike37/serverless-step-functions#22]
Step Functions is supported by cloudformation.
This could be part of the stack so we could use cross stack references for example.
https://aws.amazon.com/about-aws/whats-new/2017/02/aws-cloudformation-adds-support-for-aws-step-functions/

**Comment by horike37** [comment]
Thank you for the suggestion @paulopontesm!
Yep. I will use cloudformation next version. And integrate with `sls deploy`command.

**Comment by justinmchase** [comment]
This is necessary to support the resolution of `Ref: AWS::AccountId` for example.

**Comment by horike37** [comment]
The feature has implemented
