### ISSUE TITLE
Issue viewing docs on serverless.com

### ISSUE THREAD

**Issue by z3dtech** [horike37/serverless-step-functions#223]
# This is a (Bug Report )

## Description

The items in the list don't display on the official docs on Chrome due to strange styling issues. 

See: 

- do this using the serverless-plugin-aws-alerts, which lets you configure custom CloudWatch Alarms against the various metrics that Step Functions publishes.
- or, you can use the built-in alarms configuration from this plugin, which gives you an opinionated set of default alarms (see below)

on https://serverless.com/plugins/serverless-step-functions/#cloudwatch-alarms

also the # tagging doesn't work because he ids are removed.

Screenshot below: 
![Screen Shot 2019-07-08 at 1 31 04 AM](https://user-images.githubusercontent.com/20992790/60795192-18e1fe00-a120-11e9-8d99-a1f05808c289.png)

**Comment by theburningmonk** [comment]
@z3dtech that seems to be an issue with the serverless.com page and how it renders our [README](https://github.com/horike37/serverless-step-functions/blob/master/README.md) from Github. Can you raise this on [this repo](https://github.com/serverless/site) instead?

**Comment by z3dtech** [comment]
Good plan.
