### ISSUE TITLE
How to find or create logicalNameOfResource for CloudFormation intrinsic functions

### ISSUE THREAD

**Issue by claytron5000** [horike37/serverless-step-functions#230]
# This is a Documentation Clarification

## Description

I'm trying to use CloudFormation intrinsic functions to access resource arn's as described in the documentation: https://github.com/horike37/serverless-step-functions#setup. In the example configuration the resource is referenced like `Fn::GetAtt: [HelloLambdaFunction, Arn]`. This is partly due to a lack of knowledge about AWS CloudFormation, but I'm not sure how that string `HelloLambdaFunction` was constructed.

In the AWS documentation this is referred to as the `logicalNameOfResource`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html. And then there's more detail here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html.

I might be mis-interpreting this, but it looks to me like the `logicalNameOfResource` is defined by the author somewhere in the template. I'm unclear where the functions are assigned this name.

**Comment by claytron5000** [comment]
Of course right after posting this I see the `name` field in the serverless docs: https://serverless.com/framework/docs/providers/aws/guide/functions/

I think the ticket still stands. I think it would help to have the function name in the example configs.

**Comment by claytron5000** [comment]
Either way is fine by me, though I'm still confused about the how the logical resource name. If I have a function like this:

```
functions:
  create-master:
    handler: create-master.handler
    name: CreateMasterFunction
```
Can I actually fetch the resource like this:

```
Fn::GetAtt: [CreateMasterFunction, Arn]
```

?

**Comment by theburningmonk** [comment]
In your case, the logical resource name would be `CreateDashMasterLambdaFunction` - the serverless framework does this when it renders your function definition into CloudFormation template (which has a convention of CamelCasing and doesn't allow characters like `-` and `_` in the logical resource name).
