### ISSUE TITLE
CloudWatch Notifications target lambda giving error ResourceNotFoundException

### ISSUE THREAD

**Issue by shahpawan** [horike37/serverless-step-functions#244]
# This is a Bug Report

## Description
I am trying the feature to trigger cloud watch events for step functions state changes mentioned here : https://github.com/horike37/serverless-step-functions#cloudwatch-notifications
As mentioned in this, I am using lambda as the target and hence added reference to ARN of a lambda from the same serverless stack

I keep getting the error : Function not found
I also tried adding the dependsOn tag on step functions, but had no luck.

Error: Function not found. (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException;

Step functions version: 2.3.0
Node version: node 6,8,10
Serverless version: 1.49.0

**Comment by theburningmonk** [comment]
Can you paste your `serverless.yml` configuration here?

**Comment by shahpawan** [comment]
Hi @theburningmonk 
I have created a test service to recreate this issue.
Here is the serverless.yml

```
service: my-step-functions

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  role: MyTestRoleARN
package:
  individually: true  

functions:

  eventparser:
    handler: lambdas/eventparser.handler
    package:
      exclude:
        - ./**
      include:
        - lambdas/eventparser.py

  eventerrorhandler:
    handler: lambdas/eventerrorhandler.handler
    package:
      exclude:
        - ./**
      include:
        - lambdas/eventerrorhandler.py

  event1:
    handler: lambdas/event1.handler
    package:
      exclude:
        - ./**
      include:
        - lambdas/event1.py

  event2:
    handler: lambdas/event2.handler
    package:
      exclude:
        - ./**
      include:
        - lambdas/event2.py


stepFunctions:
  stateMachines:
    MyStateMachine:
      name: myStateMachine-${self:provider.stage}
      definition:
        StartAt: eventparser
        States:
          eventparser:
            Type: Task
            Resource: 
              Fn::GetAtt: [eventparser, Arn]
            Catch:
              - ErrorEquals: ["Exception"]
                Next: ReturnError
            Next: ProcessEvent
          ProcessEvent:
            Type: Choice
            Choices:
            - Variable: "$.eventType"
              StringEquals: "event1"
              Next: event1
            - Variable: "$.eventType"
              StringEquals: "event2"
              Next: event2
            Default: ReturnSuccess
          event1:
            Type: Task
            Resource:
              Fn::GetAtt: [event1, Arn]
            Next: ReturnSuccess
          event2:
            Type: Task
            Resource:
              Fn::GetAtt: [event2, Arn]
            Next: ReturnSuccess
          ReturnSuccess:
            Type: Succeed
          ReturnError:
            Type: Fail
            Cause: "Invalid Event"
      notifications:
        FAILED:
          - lambda: arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:${self:service}-${self:provider.stage}-eventerrorhandler

plugins:
  - serverless-step-functions

```

I even tried adding line ```dependsOn: EventErrorHandlerLambdaFunction``` on step functions.
Still no luck.

**Comment by theburningmonk** [comment]
The way to do it is to use intrinsic functions instead (notice that the logical ID is `EventerrorhandlerLambdaFunction` not `EventErrorHandlerLambdaFunction` based on the name you gave it earlier - `eventerrorhandler`):

```
notifications:
  FAILED:
    - lambda:
        Fn::GetAtt: [EventerrorhandlerLambdaFunction, Arn]
```

**Comment by shahpawan** [comment]
Hi @theburningmonk ,
This worked.
I didn't realize that using the general formatting I used will cause the issue.
Thanks a lot.

**Comment by theburningmonk** [comment]
@shahpawan the notifications are not part of the state machine resource (they're cloudwatch events) which is why adding a `dependsOn` to the state machine doesn't help
