### ISSUE TITLE
request.files['file'] is returning filestorage object when run locally but when deployed on AWS using serverless it returns a string of the contents inside the .txt file. Which is resulting in the error "String object does not have attribute save" when I'm trying to do f.save(). Please help.

### ISSUE THREAD

**Issue by rahultappetla** [horike37/serverless-step-functions#256]
request.files['file'] is returning filestorage object when run locally but when deployed on AWS using serverless it returns a string of the contents inside the .txt file. Which is resulting in the error "String object does not have attribute save" or "String obj as no attribute filename" when I'm trying to do f.save(f.filename). Please help.

**PS : ignore the indentation in the below code. I copy pasted it in parts.**

def create_aws_event(flask_request: request, path_data: Dict, resource: str) -> Dict:
    # build our path data
    path_parameters = {}
    for p in path_data:
        path_parameters[p] = path_data[p]

    # build our query strings for the event
    query_string_parameters = {}
    # noinspection PyUnresolvedReferences
    for q in flask_request.args:
        # noinspection PyUnresolvedReferences
        query_string_parameters[q] = flask_request.args.get(q)

return {
        "resource": resource,
        "path": flask_request.path,
        "httpMethod": flask_request.method,
        "headers": {},
        "multiValueHeaders": {},
        "queryStringParameters": query_string_parameters,
        "multiValueQueryStringParameters": {},
        "pathParameters": path_parameters,
        "stageVariables": {},
        "requestContext": {},
        "body": flask_request.files,
        "isBase64Encoded": False
    }

@app.route('/uploader', methods=['GET', 'POST'])
def upload_file():

    event = create_aws_event(flask_request=request, path_data={}, resource='/uploader')
    print('EVENT:', event)

    print(event['body'])

    result = aws_doc_upload.lambda_handler(event=event, context=Context)

    return Response(result['body'], status=result['statusCode'], content_type='application/json')

**In lambda_handler :**

    elif resource == '/uploader' and method == 'POST':
        
        test = event['body']
        print("FILE: ", test)
        test.save(test.filename)

**Comment by theburningmonk** [comment]
What are you using to run a flask app in a lambda function? Some Serverless plugin? If so, your best bet is to raise an issue there, as we don't have the expertise to help you when this particular problem.

One thing that might be worth trying though, is to include whatever framework you're running (maybe flask itself?) as part of your deployment artifact so to eliminate any version differences between local and AWS.
