### ISSUE TITLE
Feature Request: Not 0 exit status when fail.

### ISSUE THREAD

**Issue by kitsuyui** [horike37/serverless-step-functions#26]
```console
$ sls invoke stepf -t hello_automation
Serverless: Start function hello_automation...


Execution Result -----------------------------------------

{ ...
  status: 'FAILED',
  input: '{}' }

Error Log ------------------------------------------------

{ cause: 'some error' }
$ echo $?
0
```

現状このように、成功・失敗にかかわらず
終了ステータスコードが 0 になっていると思います。
Unix 的な伝統にもとづき、失敗した時は 0 以外で終了するような機能があるとよいな、と思います。

**Comment by horike37** [comment]
たしかにそうですね。次バージョンでそのようにします！
ありがとうございます！

**Comment by kitsuyui** [comment]
@horike37 ありがとうございます！

**Comment by kitsuyui** [comment]
@horike37 
https://github.com/horike37/serverless-step-functions/pull/29 

お願いするばかりでは申し訳ないので、こちらでも取り組んでみました。
宜しければ。 :)

**Comment by horike37** [comment]
@kitsuyui 
ありがとうございます！マージしました！

**Comment by horike37** [comment]
https://github.com/horike37/serverless-step-functions/releases/tag/0.4.2
0.4.2にこの内容を加えてリリースしました。
