### ISSUE TITLE
Unable to use cross-stack variable for state machine definition's role parameter

### ISSUE THREAD

**Issue by stevecaldwell77** [horike37/serverless-step-functions#262]
# This is a (Bug Report / Feature Proposal)

## Description

Starting in v2.5, you are no longer able to import a variable from a different stack to use for a state machine's role, using `Fn::ImportValue`.

With a definition like:
```
stepFunctions:
  stateMachines:
    hellostepfunc1:
      ...
      role:
        "Fn::ImportValue": StateMachineRoleArn
```

The following error occurs:

```
ValidationError: child "role" fails because ["role" must be a string, "Fn::ImportValue" is not allowed, "Fn::ImportValue" is not allowed]
```

I've created a repository you can use to re-create the issue:
https://github.com/stevecaldwell77/serverless-step-functions-import-role-issue

Similar or dependent issues:
* #253

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.53.0
* ***The Plugin Version you're using***: 2.8.2
* ***Operating System***: MacOS

**Comment by stevecaldwell77** [comment]
Confirmed, bug is now fixed. Thanks @theburningmonk!

**Comment by theburningmonk** [comment]
no probs!
