### ISSUE TITLE
Bug in compileIamRole.js when no functions node in serverless.yml

### ISSUE THREAD

**Issue by antherkiv** [horike37/serverless-step-functions#265]
# This is a (Bug Report / Feature Proposal)
Bug Report
## Description

For bug reports:
* What went wrong?
Type error in line 341 has been throw during deploy
e.g.

TypeError: state.Resource.startsWith is not a function

This Line:
`if (isIntrinsic(state.Resource) || state.Resource.startsWith('arn:aws:lambda')) {`

* What did you expect should have happened?
Deploy with no issues

* What was the config you used?
I'm referencing functions by importing the arn value and with no function node in servrless.yml just the stepfunction definition.

* What stacktrace or error message from your provider did you see?
`...
Serverless: Packaging service...
 
  Type Error ---------------------------------------------
 
  TypeError: state.Resource.startsWith is not a function
      at _.flatMap (/home/****/***//node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:335:59)
...
`

**Comment by theburningmonk** [comment]
@antherkiv can you paste your step function definition here? Sounds like you might be missing a `Resource` field for a `Task` state.

**Comment by antherkiv** [comment]
Yeah, it's my fault I found the error in the step function definition, was a typo in the Fn::ImportValue.

Thanks, I'm so sorry.

**Comment by theburningmonk** [comment]
No probs, glad it's solved!
