### ISSUE TITLE
Lambda function in a Map don't get added to the IAM role

### ISSUE THREAD

**Issue by ycarel** [horike37/serverless-step-functions#272]
This is a Bug Report

## Description

Lambda functions that are used only inside a Map state don't get added to the Lambda execution IAM role

Sample state machine definition (I skipped the part that are not interesting)
...
WriteToS3PartitionFunction:
    handler: writeToS3Partition/writeToS3Partition.lambda_handler
    runtime: python3.6
...
stepFunctions:
  stateMachines:
...
LaunchWriteToS3PartitionsMap:
            Type: Map
            ItemsPath: $.objects
            Parameters:
              "datalake.$": $.datalake
              "country.$": $.country
              "object.$": $$.Map.Item.Value
            Iterator:
              StartAt: WriteToS3Partitions
              States:
                WriteToS3Partitions:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [WriteToS3PartitionFunction, Arn]
                  End: true
            End: true

The automatically created IamRoleStateMachineExecution IAM role doesn't contain the required definition that allow the execution of the WriteToS3PartitionFunction.

I ended up adding a dummy state to make the IAM role include the lambda
DummyState:
            Type: Task
            Resource:
              Fn::GetAtt: [WriteToS3PartitionFunction, Arn]
            Next: WriteRecordToCache

**Comment by theburningmonk** [comment]
hi @ycarel what version are you running? This was added in v2.8.0

**Comment by ycarel** [comment]
I’m using version 2.6.1
I will try to update and get back to you.

Thanks
Yair Carel

**Comment by theburningmonk** [comment]
@ycarel any luck?

**Comment by ycarel** [comment]
Yes.
The new version did indeed fix the issue.

Thanks for your help

Yair
