### ISSUE TITLE
Use with Serverless Framework Core 1.60.5 breaks Deployment logical name

### ISSUE THREAD

**Issue by uneco** [horike37/serverless-step-functions#294]
# This is a Bug Report

### What went wrong?

resource name of the API Gateway Deployment in generated template is changed to `ApiGatewayDeploymentundefined`.
This will also prevent the second and subsequent API deployments.

### What did you expect should have happened?

it should be `ApiGatewayDeployment1578119140046`.
This change is the cause of this problem https://github.com/serverless/serverless/commit/5325cbd784ffc3da6917a14a134eff3a0c65acd3

## Additional Data
* ***Serverless Framework Core Version you're using***:
1.60.5

* ***The Plugin Version you're using***:
2.16.0

**Comment by uneco** [comment]
Here is the simplest workaround: https://github.com/uneco/serverless-step-functions/commit/581ebe8208823187a5a88b42671651e0b16af16e
However, it is not a perfect solution in terms of plugins reverting Core changes.

```diff
diff --git a/lib/deploy/events/apiGateway/deployment.js b/lib/deploy/events/apiGateway/deployment.js
index d1aa7f8..2fa32c4 100644
--- a/lib/deploy/events/apiGateway/deployment.js
+++ b/lib/deploy/events/apiGateway/deployment.js
@@ -6,7 +6,7 @@ const BbPromise = require('bluebird');
 module.exports = {
   compileDeployment() {
     this.apiGatewayDeploymentLogicalId = this.provider.naming
-      .generateApiGatewayDeploymentLogicalId();
+      .generateApiGatewayDeploymentLogicalId((new Date()).getTime().toString());

     _.merge(this.serverless.service.provider.compiledCloudFormationTemplate.Resources, {
       [this.apiGatewayDeploymentLogicalId]: {
```

**Comment by theburningmonk** [comment]
@uneco mm... that's pretty annoying that they changed things again. I think a more future-proof solution would be to scan through the generated resources and look for the deployment resource by type, and use the actual logical ID, rather than relying on this internal method that keeps changing.

**Comment by theburningmonk** [comment]
@uneco I just put together a test project, and while I'm able to reproduce the issue with the logical ID, it hasn't stopped me from making subsequent deployments. What error are you seeing in the second and subsequent API deployments?

**Comment by uneco** [comment]
@theburningmonk 
No error occurs. CloudFormation cannot detect any changes to the deployment and nothing happens. Originally, a random ID is specified to avoid this.

---

1st time:
```
ApiGatewayDeployment1578119140046 (DELETE)
↓
ApiGatewayDeploymentundefined (CREATE)
```

<img width="1025" alt="スクリーンショット 2020-01-05 1 43 33" src="https://user-images.githubusercontent.com/603523/71768800-1fc9bc00-2f5d-11ea-9b6d-25fb54c5361a.png">

2nd time:
```
ApiGatewayDeploymentundefined
↓
ApiGatewayDeploymentundefined
```

<img width="909" alt="スクリーンショット 2020-01-05 1 45 17" src="https://user-images.githubusercontent.com/603523/71768807-2eb06e80-2f5d-11ea-83d1-39d95045852f.png">

**Comment by theburningmonk** [comment]
@uneco ah, gotcha, thanks!
