### ISSUE TITLE
AWS Region not read from provider.region

### ISSUE THREAD

**Issue by kennu** [horike37/serverless-step-functions#3]
Great plugin! I noticed one problem. I have this in serverless.yml:

    provider:
      stage: dev
      region: eu-west-1
      profile: xxx

When I run sls deploy stepf, the state machine itself is deployed to *eu-west-1*, but the Lambda ARNs point to *us-east-1* so they don't work and execution fails.

It works correctly when I manually specify `sls deploy stepf -r eu-west-1` .

**Comment by horike37** [comment]
@kennu 
Thank you! I will fix it.

**Comment by horike37** [comment]
Just fixed.
