### ISSUE TITLE
Minor issue with empty activies in v1.0.0

### ISSUE THREAD

**Issue by justinmchase** [horike37/serverless-step-functions#34]
I dont' have any activities and as a result my servlerless file looks sort of like:
```
stepFunctions:
  stateMachines:
    hello: ...
```

As a result I am getting this error:
```
Serverless: Packaging service...

  Serverless Error ---------------------------------------

     activities property is not an array Please check the
     README for more info.
```

Simply changing my file to this fixes it:
```
stepFunctions:
  activities: []
  stateMachines:
    hello: ...
```

But it seems like activities should default to an empty array automatically instead of null in this case.

**Comment by horike37** [comment]
@justinmchase 
Thanks for the report! I have also reproduced on my machine. 
will fix ASAP..

**Comment by horike37** [comment]
Just fixed and released new version.
https://github.com/horike37/serverless-step-functions/releases/tag/1.0.1
