### ISSUE TITLE
Serverless service prefix not included in state machine name

### ISSUE THREAD

**Issue by kennu** [horike37/serverless-step-functions#4]
When I deploy "myproject" with Serverless, Lambda functions are prefixed with the service name and suffixed by stage, so they are called "myproject-myfunc-dev" etc.

Perhaps serverless-step-functions should also do the same, so that state machines are called "myproject-mymachine-dev" instead of just "mymachine-dev"? Otherwise there will be conflicts.

**Comment by horike37** [comment]
@kennu 
thank you for reporting!
It is as you have pointed out. I will fix it

**Comment by horike37** [comment]
Just fixed.
