### ISSUE TITLE
Add the current `stage` name into the State Machine name

### ISSUE THREAD

**Issue by justinmchase** [horike37/serverless-step-functions#44]
I have multiple stages deployed to my account and currently this:
```
stepFunctions:
  stateMachines:
    Example: ...
```

Will create a StateMachine like this:
```
ExampleStepFunctionsStateMachine-QWUYMJP6O0QH
```

The problem is that I have maybe half a dozen stages in a single account and I cannot tell the difference between them now. I would have 6 `ExampleStepFunctionStateMachine-*` state machines and there is no way to distinguish which is staging and which is prod for example.

What would be really nice is just if the name of the created state machine also had the stage in it, for example:
```
ExampleProdStepFunctionsStateMachine-QWUYMJP6O0QH
ExampleStagStepFunctionsStateMachine-IOUME4NGKVE2
```

etc.

**Comment by horike37** [comment]
Thank you for the suggestion @justinmchase !
Unfortunately you can not specify a statemachine name in CloudFormation as far as I read the following doc(sls deploys through CF).
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html

However, you can specify stage when running sls command to get difference between them.
For example: `sls invoke stepf --stage <your stage name>`

Do you mean what you said that you want to get the difference inside Lmambda functions source code?

**Comment by justinmchase** [comment]
We are using stages, I have `prod` and `stag` stages as well as one stage per developer. The problem I'm having is that if we publish our step functions all with the name `Example` but with different stages, if I then go to the console to look at errors or try to find a currently executing step function what I end up with is something like this in the UI:

```
ExampleStepFunctionsStateMachine-QWUYMJP6O0QH
ExampleStepFunctionsStateMachine-IOUME4NGKVE2
ExampleStepFunctionsStateMachine-AWUYMJP6O4YZ
ExampleStepFunctionsStateMachine-JKPME4NGKVM3
ExampleStepFunctionsStateMachine-YHUYMJP6O09I
ExampleStepFunctionsStateMachine-LHRME4NGKVL4
```

Now I want to find the `prod` state machine... which one is it? I don't have a way to visually distinguish between them because they all have the same name.

**Comment by horike37** [comment]
thank you for explaining. I understand.
However, I can't think of any sensible ideas to solve this..
Do you have any ideas?

**Comment by justinmchase** [comment]
The only thing I can think of is basically while you're generating the cloud formation sections, just add the stage name into the names of the step functions.

For example [here](https://github.com/horike37/serverless-step-functions/blob/master/lib/yamlParser.js#L41):
```js
getAllStateMachines() {
    if (Object.prototype.toString.call(this.serverless.service.stepFunctions.stateMachines)
      !== '[object Object]') {
      const errorMessage = [
        'stateMachines property is not an object',
        ' Please check the README for more info.',
      ].join('');
      throw new this.serverless.classes
      .Error(errorMessage);
    }
    return Object.keys(this.serverless.service.stepFunctions.stateMachines);
  },
```

Could be changed to be more like:
```js
getAllStateMachines() {
    if (Object.prototype.toString.call(this.serverless.service.stepFunctions.stateMachines)
      !== '[object Object]') {
      const errorMessage = [
        'stateMachines property is not an object',
        ' Please check the README for more info.',
      ].join('');
      throw new this.serverless.classes
      .Error(errorMessage);
    }
    return Object
        .keys(this.serverless.service.stepFunctions.stateMachines)
        .map(sm => sm + this.stage);
  },
```

So basically everywhere you get the stateMachine name out of the yaml, just append the stage to it. I'm not familiar enough with the code to make a PR yet, what do you think about that in general?

**Comment by icarus-sullivan** [comment]
@horike37 I made a PR to add a custom Name, which falls back to how the naming convention is now. 

* It was pointed out I can reference the Outputs > Value > Ref as an environment variable so I am currently using that in separate Lambda's. 

However, it would make reading the stateMachines in the AWS Console much easier.

**Comment by justinmchase** [comment]
#50

**Comment by horike37** [comment]
have merged it!
