### ISSUE TITLE
is it possible to keep the "Sample statemachines setting in serverless.yml" section into the README?

### ISSUE THREAD

**Issue by kararade** [horike37/serverless-step-functions#47]
hey!

I was searching how to use another `types` like `catch` , `wait` and `parallel` with this plugin sadly with any good information until found this one https://github.com/horike37/serverless-step-functions/blob/6d3ebb3acc149e975c77c4db41fb4a95d014b7fb/README.md#sample-statemachines-setting-in-serverlessyml . Actually I fixed my issues following those examples.

I think those examples are pretty useful to have at hand. 

What do you think to keep it into the master `README` of this plugin?

Thanks!

**Comment by horike37** [comment]
Thank you for opening @kararade !
All right!

I thought that you should read the AWS documents how to write AWS state language at that time, so removed  those examples.
However i will write those in Readme if those makes it easy to understand how to use

**Comment by horike37** [comment]
done.

**Comment by kararade** [comment]
thanks!
