### ISSUE TITLE
Don't remove superceded State machines

### ISSUE THREAD

**Issue by viz** [horike37/serverless-step-functions#54]
I'd like to suggest that we don't remove a superceded state machine when it is modified and redeployed.

It's highly likely, over the life of a solution employing step functions, that a step function will be modified where there are completed and in-progress executions. I understand that the step function won't be deleted until all executions are complete, however we want to keep the history of a step function and retain access to completed executions.

With the current behaviour of the plugin we remove the old version as soon as all executions are completed (at least as far as I can see).

Interested in other opinions or other ways to retain history of executions.

**Comment by horike37** [comment]
Thank you also for opening up this @viz! 

>I'd like to suggest that we don't remove a superceded state machine when it is modified and >redeployed.
I agree. However, the deleting process is the specification of CloudFromation (Serverless core and this plugin deploy via CloudFormation)

>however we want to keep the history of a step function and retain access to completed executions.
In order to realize this, executions log may put out other strage(like S3).
Does anyone have good suggestion to solve this issue?

**Comment by viz** [comment]
Clearly we'd have a record of the previous state machine configuration from our repo and build system, so as you highlight, perhaps the answer is to find a way to archive the execution history to S3. Note that it would be important for that history to be unambiguously associated with the specific configuration of the state machine at the time.

I'll think about how we might so this.

**Comment by viz** [comment]
correction: what I've realised is that an execution of a 'deleting' step function isn't allowed to complete - on it's next state transition after the step function enters the 'deleting' state the execution aborts with cause being 'The state machine xxx has been deleted'.

This becomes a problem because any change to our step function results in deleting the old one and creating a new one. Perhaps this is because we create a unique name when the step function is deployed.

@horike37 do you know whether the cloud formation config would update instead if we didn't use a unique name or does it always delete the old and create a new step function?

**Comment by theburningmonk** [comment]
The executions are immutable even when you update the definition of a state machine. However, if you change the Lambda code as well then they will pick up the new Lambda code. To lock an execution to the exact version of the function (also immutable) it was deployed with, you can use the `useExactVersion` config option, see [here](https://github.com/horike37/serverless-step-functions#blue-green-deployment) for more details.
