### ISSUE TITLE
Accessing provisioned name of a state machine

### ISSUE THREAD

**Issue by viz** [horike37/serverless-step-functions#55]
Does anyone have a way to access the provisioned name of a state machine?

The situation I'm considering is where we modify a state machine and re-deploy. A new state machine is created with a new postfix. We have an API function that creates a new execution that needs access to the state machine name in order to create the execution. When there are multiple state machines names [machine_name]-XXXXX with different postfix hashes we can't identify the new state machine in order to create a new execution.

Note also that the old state machine is in 'deleting' state and we can't create new executions for that either.

Do we need to create two projects, one provisioning the state machines and one provisioning everything else and using the Cloud Formation ability to reference outputs across stacks? (haven't done this before).

**Comment by horike37** [comment]
Thank you for opening up this issue @viz !
I may not understand the essence of the problem what you stated.

As far as reading the following document, we can get the statemachine name from logical id by using `{ "Fn::GetAtt": ["MyStateMachine", "Name"] }`.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html
Have you try this yet?

**Comment by viz** [comment]
Sorry, I didn't explain it clearly :-)

Here is the scenario:
In my servereless.yml I have a state machine defined named `masterStateMachine`. When I deploy cloud formation creates a state machine named `masterStateMachine-QSP9911WC0L7`.

I have a lambda function (linked to an API endpoint) that first lists the state machines available, then uses a regex to find `masterStateMachine*` so that it can extract the ARN and use this to create a new execution.

Let's assume that there is at least one open execution for this state machine, and I machine an update to my state machine and re-deploy my serverless project. Cloud Formation now creates a new state machine named `masterStateMachine-YPX8677QR4P9` but the existing machine `masterStateMachine-QSP9911WC0L7` is still present because it has running executions.

Now when my lambda function tries to create a new execution it lists the state machines and the regex finds two matching state machines.

Without knowing the name of the second created state machine, I'll have to use the created date returned by the `listStateMachines` to determine which one is the latest.

SO! my question above was really asking - is there a way, from serverless, that I can determine the name of the provisioned stateMachine so that I can pass it into the lambda function and avoid the regex and sorting by created date?

I'm assuming the answer is no since the name is created by Could Formation and not available to serverless to pass in as an environment variable...

**Comment by horike37** [comment]
@viz 
Thank you for explaination. I have understood what you stated.
It is possible to pass an statemachine arn via environment variable.

Have you seen Tips section in `README`? If not, cloud you see that and try it.
I have written how to pass Lambda function an arn via environment variable as titled `How to specify the stateMachine ARN to environment variables`.

**Comment by viz** [comment]
@horike37 - thanks! that worked like a charm :-)

Sorry I didn't go over the readme properly...

**Comment by horike37** [comment]
@viz 
Glad to hear that figured out your problem!
