### ISSUE TITLE
Invalid principal deploying IamRoleStateMachineExecution Role

### ISSUE THREAD

**Issue by robizz** [horike37/serverless-step-functions#59]
Hi,
using 
**serverless@1.16.1
serverless-step-functions@1.0.2**

found a problem while deploying a state machine

`	
IamRoleStateMachineExecution	Invalid principal in policy: "SERVICE":"states.${opt:region, self:custom.defaultRegion}.amazonaws.com"
`

I'm a noob at nodejs but I managed to fix it doing in the `serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js` file :

 \- `iamRoleStateMachineExecutionTemplate.replace('[region]', this.region)
`
 \+ `iamRoleStateMachineExecutionTemplate.replace('[region]', this.options.region)
`

please see the attached patch
[local_history.patch.txt](https://github.com/horike37/serverless-step-functions/files/1115736/local_history.patch.txt)

sorry for not submitting  PR, but I'm not sure if the fix is right :)

Regards and keep up with this good work!

Roberto

**Comment by horike37** [comment]
@robizz 
Thank you for opening this issue!
First, I'd like to get the step to reprpduce of this bug.

Could you show me your using all of serverless.yml?

**Comment by robizz** [comment]
Hi, here my sample serverless.yml
[serverless.yml.txt](https://github.com/horike37/serverless-step-functions/files/1121277/serverless.yml.txt)

**Comment by horike37** [comment]
Thank you for sending me the file @robizz !
I have reproduced the same problem on my laptop.

Then your fix looks good. Could you please give me PR with the fix?

**Comment by horike37** [comment]
Hey @robizz ! I have merged your awsome fix and v1.0.5 has been released yesterday.
so maaaaany thanks!
