### ISSUE TITLE
Ability to pass api path parameters to state machine

### ISSUE THREAD

**Issue by shahpawan** [horike37/serverless-step-functions#71]
Hi,
I have attached a serverless.yml and one simple python lambda to explain the issue.

In serverless config, please notice the event http path which is /{namespace}/event/{eventType}

Usually when I use such a path in my serverless.yml for an http endpoint for lambda (without step functions), I can read the path parameters namespace and eventType in lambda as event["pathParameters"]["namespace"].
But when I use this with step functions , pathParameter never reaches the lambda.

Am I missing something here?
[Simple-step-function-example.zip](https://github.com/horike37/serverless-step-functions/files/1185580/Simple-step-function-example.zip)

**Comment by horike37** [comment]
@shahpawan 
Thank you for opening this up!
We didn't consider path parameters when we implemented http event. We should add the feature into the plugin

**Comment by horike37** [comment]
Closing since API event on step function can be used only and only to trigger state machine.
