### ISSUE TITLE
Question: Schedule Event

### ISSUE THREAD

**Issue by jnst** [horike37/serverless-step-functions#74]
# This is a Question

## Description
Was the schedule event supported?

* https://github.com/horike37/serverless-step-functions/issues/48
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

**Comment by horike37** [comment]
Yup. Now I am implementing.
Let me take it for a couple days!

**Comment by jnst** [comment]
Great! I've been setting it up manually so it will be very useful!!
