### ISSUE TITLE
Serverless Step Functions offline

### ISSUE THREAD

**Issue by vicneanschi** [horike37/serverless-step-functions#81]
# This is Feature Proposal

## Description
Please add support for offline mode.

This would be very helpful to test serverless configuration with this plugin locally in offline mode.

It would require an implementation of [State Machine](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-states.html)  which is described by [Amazon States Language](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html).

For starters it would be enough to support just one [type of tasks](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-tasks.html) - [Lambda Function](http://docs.aws.amazon.com/step-functions/latest/dg/tutorial-creating-lambda-state-machine.html).

Thanks!

**Comment by horike37** [comment]
Thank you for the suggestion @vicneanschi :+1: 
That's a great idea, I'd love to introduce the offline mode functionality :tada: 
However, I don't have the plan how to implement, so hopefully any feedback for implementation.

**Comment by vkkis93** [comment]
Hello Guys 
I wrote plugin which can help you run step functions offline/locally.

https://github.com/vkkis93/serverless-step-functions-offline

At this moment plugin in beta version, but it support a few states like Wait, Choice, Parallel, Task. Some of states has limitation support.
Plugin support only runtime node.js and works only with callback. 
Currently does not work with context object.

**Comment by horike37** [comment]
AWESOME @vkkis93 !!! That's a super great plugin!
Thank you for letting us know!

You might want to post serverless.com blog if you want to promote the plugin.
https://github.com/serverless/blog

**Comment by vkkis93** [comment]
@horike37 good idea, but currently plugin in beta and need some time for testing.
When plugin will be stable - I will post on serverless.com.
I want to get some feedback from users .

**Comment by horike37** [comment]
Sounds great!
Yes! I will try the plugin too.

**Comment by horike37** [comment]
Closing this issue since the awesome plugin has been released :1st_place_medal: :smile:

**Comment by WagnerSilveira** [comment]
@horike37, the plugin is not under maintenance any more, what about if we incorporate the plugin code here?

**Comment by horike37** [comment]
Hey, @WagnerSilveira . Thank you for this comment. Do you mean that you incorporate the features that the Serverless Step Functions Offline offers into Serverless Step Functions?
