### ISSUE TITLE
Statemachine doesn't get created if manually deleted after deploy

### ISSUE THREAD

**Issue by cliffxuan** [horike37/serverless-step-functions#84]
If I create a state machine using serverless-step-functions plugin, and then manually delete it from AWS, `serverless deploy` does not create the state machine again, nor does it error.

All I get is this with an empty endpoint.
<img width="278" alt="screen shot 2017-11-08 at 12 11 35 pm" src="https://user-images.githubusercontent.com/640204/32548486-b45a0ba6-c47d-11e7-817e-3151554344fd.png">

**Comment by horike37** [comment]
Thank you for reporting @cliffxuan :+1: 
Seems that the concurrency of deployment would be broken by manually deleting.
For creation and deletion of deployment, you should do via `sls deploy` and `sls remove`.(one of our main goals is that you could be doing all stuff of serverless architecture via command line)

**Comment by cholletisuman** [comment]
any fix for this
