### ISSUE TITLE
This plugin creates a random ID after the name 

### ISSUE THREAD

**Issue by syedautherabbas** [horike37/serverless-step-functions#85]
Even after specifying the name as per docs , it appends a Unique IDentifier to the name. It should not.

**Comment by horike37** [comment]
Thanks reporting @syedautherabbas :+1: 
CloudFormation adds the random ID rather than this plugin, which set CloudFormation behind the scene.

We can't resolve this issue since this is on AWS end.

**Comment by syedautherabbas** [comment]
I've been using serverless for quite a while now and the way it happens is if you do not supply any custom names , CF adds a ID to the resource.

**Comment by rplute** [comment]
@syedautherabbas , just providing a little more context on why this is happening.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html

It looks like via CloudFormation, you can only define a StateMachine via the `DefinitionString` and `RoleArn`. There is no way yet via CloudFormation to provide a name. As such, CloudFormation returns the name with a unique Id at the end. Because this plug-in uses CloudFormation to create the StateMachine, it's confined by CloudFormation's own limitations and also returns a name with an appended unique Id.

Example:
```yaml
{ "Fn::GetAtt": ["MyStateMachine", "Name"] }

# returns a value similar to:
MyStateMachine-ABCDEFGHIJ1K
```

But looking at the [Step Functions API documentation](http://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateStateMachine.html), it looks like you can provide a name that way. Why AWS doesn't support this via CloudFormation is beyond me.

**Comment by syedautherabbas** [comment]
@rplute, thanks for explaining this to me, I was plain baffled as to why this plugin doesn't support it like other plugins.I guess its just because it's very nascent. hoping to see improvements in the future. 
Also , plus 1 for this cool plugin! saves a ton of time

**Comment by rplute** [comment]
@syedautherabbas , after my own investigation, it seems like an older version of this library appears to do the trick:

https://github.com/horike37/serverless-step-functions/releases/tag/0.4.2

You'll have to read the README on the differences, but it seems to create names without the unique ID. It requires a second step from `sls deploy`. You need to do something like, `sls deploy stepf statemachines` afterward. It generates the state machine name as: `service + stage + state`.

Different syntax in serverless, too:

```yaml
stepFunctions:
  role: (has to be a string)

  stateMachines:
    myFunc:
      ${file(state_machine.yml)}
```

**Comment by syedautherabbas** [comment]
@rplute , hey thanks really , i will take a look  at this and keep  you posted.

**Comment by rplute** [comment]
@syedautherabbas, update: AWS just added `update` support for State Machines in CloudFormation. Someone already filed an [issue](https://github.com/horike37/serverless-step-functions/issues/87) for this library and suggested a feature request. I just made a [PR](https://github.com/horike37/serverless-step-functions/pull/88) with the added functionality, but would love @horike37 's feedback!

**Comment by syedautherabbas** [comment]
with the new feature add  , cant i just keep the name without adding the ID ?

**Comment by horike37** [comment]
Hi @syedautherabbas
I just released v1.3.0, which allows you to keep the name without the random-ID by specifying `name` statement in serverless.yml.

Something like this:

``` yaml
stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: ${self:service}-${opt:stage}-hellostepfunc1
```

**Comment by syedautherabbas** [comment]
Thanks!

**Comment by syedautherabbas** [comment]
horike , this still retains the random ID. I have tested this with the 1.3 release

**Comment by syedautherabbas** [comment]
Horike , did you test before confirming? I cant see any changes the way naming happens and that might be a road block

**Comment by horike37** [comment]
@syedautherabbas 
yup, I tested before confirming.
Did you specify `name` statement of `stateMachines` in serverless.yml?
If not, the random ID still is added.

**Comment by syedautherabbas** [comment]
stepFunctions:
  stateMachines:
    statemachine1:
      name: ${self:service}${opt:stage}Cases
      events:
        - http:
           path: /blahres/blahpath1
           method: post

**Comment by horike37** [comment]
I tried to deploy with using your serverless.yml, but the name has been deployed.
Did you update the plugin to v1.3.0 properly?

<img width="872" alt="2017-11-28 11 06 41" src="https://user-images.githubusercontent.com/1301012/33298886-4723e782-d42c-11e7-9b16-5277b29025cd.png">

**Comment by syedautherabbas** [comment]
/usr/lib
├── @angular/cli@1.3.2
├── angular-cli@1.0.0-beta.28.3
├── npm@5.4.2
├── serverless@1.23.0
├── serverless-pseudo-parameters@1.2.5
└── serverless-step-functions@1.3.0



I did.

**Comment by syedautherabbas** [comment]
so i resolved this by installing the plugin locally , updating the global package will not enable this feature.

**Comment by rplute** [comment]
Not saying this to lessen the severity of any global update issue, but installing locally to a project is a best practice.

**Comment by syedautherabbas** [comment]
Yeah I just put it out there so others facing something similar would not
waste time and just install locally.
