### ISSUE TITLE
Cannot invoke step function

### ISSUE THREAD

**Issue by northcoders-james** [horike37/serverless-step-functions#86]
# This is a Bug Report

## Description

serverless invoke stepf --name hellostepfunc1

gives the error:

"hellostepfunc1" stateMachine does not exists.

FWIW, in invoke.js, `stateMachineOutputKey` is `"Hellostepfunc1StepFunctionsStateMachineArn"` and `output.OutputKey`s are, in turn, `"HelloArn"
"CiaoLambdaFunctionQualifiedArn"
"HelloLambdaFunctionQualifiedArn"
"ServerlessDeploymentBucketName"` so `this.stateMachineArn` never gets set to anything

**Comment by ancil26** [comment]
Facing the same issue here, how did you get around this @northcoders-james ?
