### ISSUE TITLE
version state machines

### ISSUE THREAD

**Issue by billyshambrook** [horike37/serverless-step-functions#9]
Currently this plugin replaces a state machine when deploying a change. This could be problematic for state machines that are under heavy load as it won't delete till all executions have been completed, while this also blocks any future executions till it has been deleted.

What do you think about implementing a way of versioning state machines for example, append a version to the name (.e.g myservice-dev-mystatemachine-v1)?

**Comment by horike37** [comment]
@billyshambrook 
Greate idea! Thank you very much!
I will implement the versioning statemachine feature for next release. And it is to be possible with a rollback control statemachine.

**Comment by horike37** [comment]
@billyshambrook 
Fainally, the plugin is to deploy through CloudFormation. Therefore it can not manage statemachine 
version control individually.
I appreciate your great suggestion, but I will skip this feature this time.

**Comment by tofredi** [comment]
Hi @billyshambrook, have you found a solution for this?
What happens when a new version of the state machine is deployed and we discover a bug in this version?
Is there any way to do a rollback to the previous state machine version?

Regards
