### ISSUE TITLE
SNS gets deleted

### ISSUE THREAD

**Issue by agandhinit** [horike37/serverless-step-functions#93]
# This is a Bug Report

## Description

* What went wrong? - I have a lambda which i deploy, It refers to a SNS which is created during the deployment. In this lambda i create the SNS through serverless. The lambda and the SNS both  belong to the same stack.
Now i deploy another lambda which uses the same SNS, however now I refer to the SNS as an existing topic providing arn. During this deployment serverless deletes the topic.
SNS gets deleted with deployment
* What did you expect should have happened? - The SNS stays intact.
* What was the config you used? Providing the config for the second lambda - 

`

    step-trigger:

      handler: lambdas/stepfn-trigger/index.handler

      memorySize: 1536

      timeout: 30

      events:

        - sns:

           arn: arn:aws:sns:us-east-1:12323223232:recordingassets

           topicName: recordingassets

           displayName: recordingassets

`

**Comment by horike37** [comment]
Hi, @agandhinit thank you for opening this issue :smile: 
This plugin doesn't have SNS event feature, so root cause would be the Framework core if that's a bug in a source code.

You might want to create another issue on Serverless repository.
